enum ProgressClass { crescimentoReal, manutencaoEstrategica, vitoriaTatica, disciplina }

enum ImperialOrderDoctrine { cofreNegro, laminaRubra, tronoDourado, conclave }

enum ImperialRank { ferro, bronze, prata, ouro, onix }

enum PenaltyLevel { none, warning, severe, critical }

class ImperialTitle {
  const ImperialTitle({
    required this.name,
    required this.rank,
    required this.temporary,
    required this.requirement,
    required this.effect,
  });

  final String name;
  final ImperialRank rank;
  final bool temporary;
  final String requirement;
  final String effect;
}

class ImperialCurrencies {
  const ImperialCurrencies({
    required this.gloria,
    required this.disciplina,
    required this.influencia,
    required this.selos,
  });

  final int gloria;
  final int disciplina;
  final int influencia;
  final int selos;

  ImperialCurrencies copyWith({int? gloria, int? disciplina, int? influencia, int? selos}) {
    return ImperialCurrencies(
      gloria: gloria ?? this.gloria,
      disciplina: disciplina ?? this.disciplina,
      influencia: influencia ?? this.influencia,
      selos: selos ?? this.selos,
    );
  }

  Map<String, dynamic> toMap() => {
        'gloria': gloria,
        'disciplina': disciplina,
        'influencia': influencia,
        'selos': selos,
      };

  factory ImperialCurrencies.fromMap(Map? map) => ImperialCurrencies(
        gloria: map?['gloria'] as int? ?? 0,
        disciplina: map?['disciplina'] as int? ?? 0,
        influencia: map?['influencia'] as int? ?? 0,
        selos: map?['selos'] as int? ?? 0,
      );
}

class ProgressionState {
  const ProgressionState({
    required this.order,
    required this.currencies,
    required this.level,
    required this.xp,
    required this.dailyImpactHash,
    required this.storeUnlocks,
  });

  final ImperialOrderDoctrine order;
  final ImperialCurrencies currencies;
  final int level;
  final int xp;
  final Map<String, int> dailyImpactHash;
  final List<String> storeUnlocks;

  static const initial = ProgressionState(
    order: ImperialOrderDoctrine.conclave,
    currencies: ImperialCurrencies(gloria: 0, disciplina: 0, influencia: 0, selos: 0),
    level: 1,
    xp: 0,
    dailyImpactHash: {},
    storeUnlocks: [],
  );

  ProgressionState copyWith({
    ImperialOrderDoctrine? order,
    ImperialCurrencies? currencies,
    int? level,
    int? xp,
    Map<String, int>? dailyImpactHash,
    List<String>? storeUnlocks,
  }) {
    return ProgressionState(
      order: order ?? this.order,
      currencies: currencies ?? this.currencies,
      level: level ?? this.level,
      xp: xp ?? this.xp,
      dailyImpactHash: dailyImpactHash ?? this.dailyImpactHash,
      storeUnlocks: storeUnlocks ?? this.storeUnlocks,
    );
  }

  Map<String, dynamic> toMap() => {
        'order': order.name,
        'currencies': currencies.toMap(),
        'level': level,
        'xp': xp,
        'dailyImpactHash': dailyImpactHash,
        'storeUnlocks': storeUnlocks,
      };

  factory ProgressionState.fromMap(Map? map) {
    if (map == null || map.isEmpty) return initial;
    return ProgressionState(
      order: ImperialOrderDoctrine.values.byName(map['order'] as String? ?? ImperialOrderDoctrine.conclave.name),
      currencies: ImperialCurrencies.fromMap(map['currencies'] as Map?),
      level: map['level'] as int? ?? 1,
      xp: map['xp'] as int? ?? 0,
      dailyImpactHash: (map['dailyImpactHash'] as Map?)?.map((k, v) => MapEntry(k.toString(), v as int)) ?? {},
      storeUnlocks: (map['storeUnlocks'] as List?)?.cast<String>() ?? const [],
    );
  }
}

class CampaignArc {
  const CampaignArc({
    required this.id,
    required this.supremeGoal,
    required this.weeklyMissions,
    required this.bossChallenge,
    required this.autoGenerated,
  });

  final String id;
  final String supremeGoal;
  final List<String> weeklyMissions;
  final String bossChallenge;
  final bool autoGenerated;
}

class StoreItem {
  const StoreItem({
    required this.id,
    required this.name,
    required this.category,
    required this.price,
    required this.currency,
    required this.effect,
    required this.minLevel,
  });

  final String id;
  final String name;
  final String category;
  final int price;
  final String currency;
  final String effect;
  final int minLevel;
}
